# Generated by Django 5.0.7 on 2024-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='dfees',
            field=models.FloatField(default=0),
        ),
    ]
