# Generated by Django 5.0.7 on 2024-07-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_departmentmodel_dfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='dfees',
            field=models.FloatField(default=None),
        ),
    ]
